- name: TASK01 - MAKE SURE THAT PIP IS INSTALL
  command: "pip --version"
  register: is_pip
  ignore_errors: yes

- name: TASK02 - DOWNLOAD get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp
  when: is_pip.failed

- name: TASK03 - INSTALLING PIP
  command: "python /tmp/get-pip.py"
  when: is_pip.failed

- name:  TASK04 - DELETING get-pip.py
  file: state=absent path=/tmp/get-pip.py
  when: is_pip.failed
- name: Install python
  homebrew: name=python

- name: Install python3
  homebrew: name=python3

- name: Install ag
  homebrew: name=the_silver_searcher

- name: Install curl
  homebrew: name=curl

